name: setup playwright container
description: |
  This action is responsible for installing essential apps and configuring environment variables.

inputs:
  require-m2-settings:
    description: 'set "true" as a string if you need to configure .m2/settings.xml'
    required: false
    default: 'false'
  gh_pat:
    description: 'GitHub Personal Access Token'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt-get install -y \
          make \
          gettext-base \
          fonts-ipafont-gothic \
          fonts-ipafont-mincho \
          libasound2-dev \
          libc-dev-bin \
          libc-devtools \
          libc6-dev \
          libcrypt-dev \
          libgd3 \
          libjpeg-turbo8-dev \
          libjpeg8-dev \
          libnsl-dev \
          libtirpc-dev \
          linux-libc-dev \
          manpages \
          manpages-dev \
          rpcsvc-proto \
          liba52-0.7.4 \
          libgraphene-1.0-0 \
          libmpeg2-4 \
          libopencore-amrnb0 \
          libopencore-amrwb0 \
          libsidplay1v5

    - name: Export environment variables
      shell: bash
      run: |
        echo "JAVA_TOOL_OPTIONS=\"-Duser.home=${HOME}\"" >> $GITHUB_ENV

    - name: Configure Maven settings
      shell: bash
      if: inputs.require-m2-settings == 'true'
      run: |
        mkdir -p ~/.m2
        envsubst < ./.github/m2_settings.template.xml > ~/.m2/settings.xml
      env:
        GH_USERNAME: ${{ github.actor }}
        GH_PAT: ${{ inputs.gh_pat }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'  # AdoptOpenJDK is now Eclipse Temurin
        java-version: '21'
        cache: 'maven'
        overwrite-settings: false
