name: Build and Verify

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/java:v1.45.1-jammy

    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            git \
            make \
            gettext-base \
            fonts-ipafont-gothic \
            fonts-ipafont-mincho \
            libasound2-dev \
            libc-dev-bin \
            libc-devtools \
            libc6-dev \
            libcrypt-dev \
            libgd3 \
            libjpeg-turbo8-dev \
            libjpeg8-dev \
            libnsl-dev \
            libtirpc-dev \
            linux-libc-dev \
            manpages \
            manpages-dev \
            rpcsvc-proto \
            liba52-0.7.4 \
            libgraphene-1.0-0 \
            libmpeg2-4 \
            libopencore-amrnb0 \
            libopencore-amrwb0 \
            libsidplay1v5

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Export environment variables
        run: |
          echo "JAVA_TOOL_OPTIONS=\"-Duser.home=${HOME}\"" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # AdoptOpenJDK is now Eclipse Temurin
          java-version: '21'
          cache: 'maven'

      - name: Build and Verify InspektorDog
        run: mvn -B -Dmaven.javadoc.skip=true verify
