name: Clean Disk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Remove unused package and /tmp folder
        run: |
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /tmp/*

