name: Docker Cleanup

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Docker Cleanup
        run: |
          docker system prune -af
          docker volume prune -f