name: Package and Run All Tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libxdamage1 libgbm1 libpango-1.0-0 libpangocairo-1.0-0 libasound2-dev libxshmfence1
          sudo apt-get install -y libwoff1 libopus0 libdbus-glib-1-2 libxtst6 libxrandr2 libxcomposite1 libxdamage1 libxshmfence1 libgbm1 libjpeg-dev libxkbfile1 libgstreamer1.0-0 libgstreamer-plugins-base1.0-0
          sudo apt-get install -y gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-gl gstreamer1.0-tools
          sudo apt-get install -y libharfbuzz-icu0 libhyphen0 libmanette-0.2-0 libflite1
          sudo apt-get install -y libgles2

      - name: Install Japanese fonts
        run: sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Playwright
        run: npm install -g playwright

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # AdoptOpenJDK is now Eclipse Temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn -Dmaven.javadoc.skip=true clean package

      - name: Run all the tests
        id: main
        run: java -jar target/autotest-caweb.jar -q 'classname:~.*' run
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: target/testResult/**
        continue-on-error: true

      - name: List generated files
        run: ls -R target

      - name: Check for failures
        if: always()
        run: |
          if [ "${{ steps.main.outcome }}" != "success" ]; then
            echo "Build failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
