name: Publish Docs

on:
  push:
    branches:
      - develop-automateDocumentPublishing
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/java:v1.45.1-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # AdoptOpenJDK is now Eclipse Temurin
          java-version: '21'
          cache: 'maven'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GH_PAT }}</password>
                    </server>
                  </servers>
                  <profiles>
                    <profile>
                      <id>github</id>
                      <repositories>
                        <repository>
                          <id>github</id>
                          <url>https://maven.pkg.github.com/moneyforward/mddoclet</url>
                        </repository>
                      </repositories>
                    </profile>
                  </profiles>
                  <activeProfiles>
                    <activeProfile>github</activeProfile>
                  </activeProfiles>
                </settings>" > ~/.m2/settings.xml

      - name: Build with Maven not Skipping JavaDoc
        run: mvn clean package test

      - name: Compile Documentation Sets
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "ci@moneyforward.com"
          git config --global user.name "MoneyForward CI"
          ./build.sh publish-wiki publish-techdocs
