name: Publish Docs

on:
  workflow_dispatch:
  push:
    branches:
      - develop-automateDocumentPublishing
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/java:v1.45.1-jammy

    steps:
      - name: Install Git
        run: apt-get update && apt-get install -y git

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-playwright-container
        with:
          require-m2-settings: 'true'
          gh_pat: ${{ secrets.GH_PAT }}

      - name: Build with Maven not Skipping JavaDoc
        run: mvn -B package

      - name: Compile Documentation Sets
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git config --global user.email "ci@moneyforward.com"
          git config --global user.name "MoneyForward CI"
          ./build.sh publish-wiki publish-techdocs
