name: Publish Docs

on:
  push:
    branches:
      - develop-automateDocumentPublishing
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/java:v1.45.1-jammy

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            git \
            fonts-ipafont-gothic fonts-ipafont-mincho \
            libasound2-dev libc-dev-bin libc-devtools libc6-dev libcrypt-dev \
            libgd3 libjpeg-turbo8-dev libjpeg8-dev libnsl-dev libtirpc-dev \
            linux-libc-dev manpages manpages-dev rpcsvc-proto liba52-0.7.4 \
            libgraphene-1.0-0 libmpeg2-4 libopencore-amrnb0 libopencore-amrwb0 \
            libsidplay1v5

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GH_PAT }}</password>
                    </server>
                  </servers>
                  <profiles>
                    <profile>
                      <id>github</id>
                      <repositories>
                        <repository>
                          <id>github</id>
                          <url>https://maven.pkg.github.com/moneyforward/mddoclet</url>
                        </repository>
                      </repositories>
                    </profile>
                  </profiles>
                  <activeProfiles>
                    <activeProfile>github</activeProfile>
                  </activeProfiles>
                </settings>" > ~/.m2/settings.xml

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # AdoptOpenJDK is now Eclipse Temurin
          java-version: '21'
          cache: 'maven'
          overwrite-settings: false

      - name: Build with Maven not Skipping JavaDoc
        run: mvn clean package test

      - name: Compile Documentation Sets
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "ci@moneyforward.com"
          git config --global user.name "MoneyForward CI"
          ./build.sh publish-wiki publish-techdocs
