on:
  pull_request:
    branches:
      - develop
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libxdamage1 libgbm1 libpango-1.0-0 libpangocairo-1.0-0 libasound2 libxshmfence1
          sudo apt-get install -y libwoff1 libvpx7 libevent-2.1-7 libopus0 libdbus-glib-1-2 libxtst6 libxrandr2 libxcomposite1 libxdamage1 libxshmfence1 libgbm1 libjpeg-dev libxkbfile1 libgstreamer1.0-0 libgstreamer-plugins-base1.0-0
          sudo apt-get install -y gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-gl gstreamer1.0-tools
          sudo apt-get install -y libharfbuzz-icu0 libhyphen0 libmanette-0.2-0 libflite1
          sudo apt-get install -y libgles2

      - name: Install Japanese fonts
        run: sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Playwright
        run: npm install -g playwright

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # AdoptOpenJDK is now Eclipse Temurin
          java-version: '21'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GH_PAT }}</password>
                    </server>
                  </servers>
                  <profiles>
                    <profile>
                      <id>github</id>
                      <repositories>
                        <repository>
                          <id>github</id>
                          <url>https://maven.pkg.github.com/moneyforward/mddoclet</url>
                        </repository>
                      </repositories>
                    </profile>
                  </profiles>
                  <activeProfiles>
                    <activeProfile>github</activeProfile>
                  </activeProfiles>
                </settings>" > ~/.m2/settings.xml

      - name: Build and Verify autotest-ca
        run: mvn clean verify

      - name: Run SonarQube scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
           args: >
             -Dsonar.projectKey=autotest-ca
             -Dsonar.projectName=autotest-ca
             -Dsonar.scm.provider=git
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
