on:
  push:
    branches:
      - develop-*
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run SonarQube scanner
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.projectKey=autotest-ca
          -Dsonar.projectName=autotest-ca
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
