name: SonarQube Data Collection

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/java:v1.45.1-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # AdoptOpenJDK is now Eclipse Temurin
          java-version: '21'
          cache: 'maven'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GH_PAT }}</password>
                    </server>
                  </servers>
                  <profiles>
                    <profile>
                      <id>github</id>
                      <repositories>
                        <repository>
                          <id>github</id>
                          <url>https://maven.pkg.github.com/moneyforward/mddoclet</url>
                        </repository>
                      </repositories>
                    </profile>
                  </profiles>
                  <activeProfiles>
                    <activeProfile>github</activeProfile>
                  </activeProfiles>
                </settings>" > ~/.m2/settings.xml

      - name: Build and Verify autotest-ca
        run: mvn clean verify

      - name: Run SonarQube scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
           # Check [1] for more details.
           # https://docs.sonarsource.com/sonarqube/latest/project-administration/analysis-scope/#example-1
           args: >
             -Dsonar.projectKey=autotest-ca
             -Dsonar.projectName=autotest-ca
             -Dsonar.scm.provider=git
             -Dsonar.java.sources=src/main/java
             -Dsonar.java.tests=src/test/java
             -Dsonar.java.binaries=target/classes
             -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/framework/jacoco.xml,target/site/jacoco/caweb/jacoco.xml,target/site/jacoco/all/jacoco.xml
             -Dsonar.sources=src/main/java
             -Dsonar.tests=src/test/java
             -Dsonar.exclusions=src/**/tests/**,src/**/examples/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
