name: SonarQube Data Collection

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/java:v1.45.1-jammy

    steps:
      - name: Install Git
        run: apt-get update && apt-get install -y git

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-playwright-container
        with:
          require-m2-settings: 'true'
          gh_pat: ${{ secrets.GH_PAT }}

      - name: Build and Verify InspektorDog
        run: mvn -B -Dmaven.javadoc.skip=true verify

      - name: Run SonarQube scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
           # Check [1] for more details.
           # https://docs.sonarsource.com/sonarqube/latest/project-administration/analysis-scope/#example-1
           args: >
             -Dsonar.projectKey=insdog
             -Dsonar.projectName=insdog
             -Dsonar.scm.provider=git
             -Dsonar.java.sources=src/main/java
             -Dsonar.java.tests=src/test/java
             -Dsonar.java.binaries=target/classes
             -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
             -Dsonar.sources=src/main/java
             -Dsonar.tests=src/test/java
             -Dsonar.exclusions=src/**/tests/**,src/**/examples/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
